### ISSUE TITLE
Make a single repository which bundles all examples to reduce release overhead

### ISSUE THREAD

**Issue by gvdongen** [restatedev/examples#1]
Single repository with general readme. 
One directory per example with a dedicated readme. 

```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/documentation/issues/112
- [ ] https://github.com/restatedev/examples/issues/2
- [ ] https://github.com/restatedev/examples/issues/4
- [ ] https://github.com/restatedev/examples/issues/6
- [ ] https://github.com/restatedev/examples/issues/14
- [ ] https://github.com/restatedev/examples/issues/15
- [ ] https://github.com/restatedev/examples/issues/17
- [ ] https://github.com/restatedev/documentation/issues/123
- [ ] https://github.com/restatedev/restate/issues/720
```

**Comment by tillrohrmann** [comment]
Done
