### ISSUE TITLE
Write handler API examples with more concise API

### ISSUE THREAD

**Issue by gvdongen** [restatedev/examples#79]
Use syntax similar to:
```
const router = restate.keyedRouter({
    greet: async (ctx: restate.RpcContext, name: string) => {
        return `Hello ${name} :-)`;
    },
});
```

to have easier overview of which routers functions are binded to.
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/examples/issues/84
- [ ] https://github.com/restatedev/examples/issues/91
- [ ] https://github.com/restatedev/examples/issues/88
```

**Comment by gvdongen** [comment]
I have done this for some of the examples. Not all of them, since it's sometimes nice to see some different ways of implementing services.
